### ISSUE TITLE
[JENKINS-30832] Seed job encounters `NoClassDefFoundError`

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/job-dsl-plugin#1906]
<p>We've been tracing some errors since upgrading to 1.39 where certain classes no longer appeared to exist. </p>

<p>We have a jar file which we add via "additionalClasspath" on our seed job.</p>

<p>On inspection of the jar, the closure files do exist.</p>

<p>```<br/>
16:37:06 java.lang.NoClassDefFoundError: com/freelancer/jobdsl/dsl/helpers/FreelancerToxWorkflowContext$_init_closure2_closure3<br/>
16:37:06 	at com.freelancer.jobdsl.dsl.helpers.FreelancerToxWorkflowContext$_init_closure2.doCall(FreelancerToxWorkflowContext.groovy:60)<br/>
```</p>

<p>The weird thing is that we tried make some changes to the source code, but the errors still point to the same location (says line 60) where it can't find the class. </p>

<p>Furthermore, we tried to track down which commit this started happening, and found it started happening when trying to clean up the classloader: <a href="https://github.com/jenkinsci/job-dsl-plugin/commit/98ad52ac530dc58156807cd7dca29f323301042c?w=1" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/job-dsl-plugin/commit/98ad52ac530dc58156807cd7dca29f323301042c?w=1</a></p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rymndhng">rymndhng</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-30832" target="_blank">Seed job encounters `NoClassDefFoundError`</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jamietanna.png" title="jamietanna's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jamietanna">jamietanna</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: job-dsl-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 4
<li><b>imported</b>: 2025-12-03
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>We've been tracing some errors since upgrading to 1.39 where certain classes no longer appeared to exist. </p>

<p>We have a jar file which we add via "additionalClasspath" on our seed job.</p>

<p>On inspection of the jar, the closure files do exist.</p>

<p>```
16:37:06 java.lang.NoClassDefFoundError: com/freelancer/jobdsl/dsl/helpers/FreelancerToxWorkflowContext$_init_closure2_closure3
16:37:06 	at com.freelancer.jobdsl.dsl.helpers.FreelancerToxWorkflowContext$_init_closure2.doCall(FreelancerToxWorkflowContext.groovy:60)
```</p>

<p>The weird thing is that we tried make some changes to the source code, but the errors still point to the same location (says line 60) where it can't find the class. </p>

<p>Furthermore, we tried to track down which commit this started happening, and found it started happening when trying to clean up the classloader: <a href="https://github.com/jenkinsci/job-dsl-plugin/commit/98ad52ac530dc58156807cd7dca29f323301042c?w=1" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/job-dsl-plugin/commit/98ad52ac530dc58156807cd7dca29f323301042c?w=1</a></p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Job DSL 1.39<br/>
Jenkins 1.631
```
</details>
